# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: eriks.gallery::lang.plugin.controllers.videos.name

# Model Form Field configuration
form: $/eriks/gallery/models/video/fields.yaml

# Model Class name
modelClass: Eriks\Gallery\Models\Video

# Default redirect location
defaultRedirect: eriks/gallery/videos

# Create page
create:
    title: eriks.gallery::lang.plugin.controllers.videos.create.title
    redirect: eriks/gallery/videos/update/:id
    redirectClose: eriks/gallery/videos

# Update page
update:
    title: eriks.gallery::lang.plugin.controllers.videos.update.title
    redirect: eriks/gallery/videos
    redirectClose: eriks/gallery/videos

# Preview page
preview:
    title: Preview Video
